In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
#tipe2.20.1 & 2.20.6
import numpy as np

#Diberikan matriks seperti berikut
matriks_A_05 = np.array([[1,0,4,3],[2,1,3,1],[1,3,0,2]])
matriks_B_05 = np.array([[3,2,1],[1,4,1],[2,3,4]])
matriks_C_05 = np.array([[0,0,1],[2,1,1],[1,4,3]])
print(matriks_A_05)
print(matriks_B_05)
print(matriks_C_05)
print(" ")
print("Tentukan hasil beberapa operasi matriks berikut")
tanya_1_05 = np.matmul(matriks_C_05,matriks_A_05)
print(tanya_1_05)
tanya_2_05 = np.matmul(matriks_B_05,matriks_A_05)
print(tanya_2_05)
tanya_3_05 = np.matmul(matriks_C_05,matriks_B_05)
print(tanya_3_05)

[[1 0 4 3]
 [2 1 3 1]
 [1 3 0 2]]
[[3 2 1]
 [1 4 1]
 [2 3 4]]
[[0 0 1]
 [2 1 1]
 [1 4 3]]
 
Tentukan hasil beberapa operasi matriks berikut
[[ 1  3  0  2]
 [ 5  4 11  9]
 [12 13 16 13]]
[[ 8  5 18 13]
 [10  7 16  9]
 [12 15 17 17]]
[[ 2  3  4]
 [ 9 11  7]
 [13 27 17]]


In [4]:
#tipe 2.20.4 & 2.20.3
import numpy as np
print ("Anda ingin membuat matriks identitas dengan ordo berapa? Batas 4-6 ")
uji_05 = float(input("Saya ingin membuat matriks identitas ukuran "))
if uji_05 == 4 :
    uji_4_05 = np.identity(4)
    print(uji_4_05)
elif uji_05 == 5 :
    uji_5_05 = np.identity(5)
    print(uji_5_05)
elif uji_05 == 6 :
    uji_6_05 = np.identity(6)
    print(uji_6_05)
print(" ")
print("Selanjutnya, jika matriks N sama dengan salah satu matriks identitas diatas, maka dapat dilihat")
bukti_05 = float(input("Saya ingin matriks N = matriks identitas..."))
print("Maka matriks N = ")
if bukti_05 == 4 :
    matriks_N_4_05 = uji_4_05
    print(matriks_N_4_05)
elif bukti_05 == 5 :
    matriks_N_5_05 = uji_5_05
    print(matriks_N_5_05)
elif bukti_05 == 6 :
    matriks_N_6_05 = uji_6_05
    print(matriks_N_6_05)

Anda ingin membuat matriks identitas dengan ordo berapa? Batas 4-6 


Saya ingin membuat matriks identitas ukuran  4


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 
Selanjutnya, jika matriks N sama dengan salah satu matriks identitas diatas, maka dapat dilihat


Saya ingin matriks N = matriks identitas... 5


Maka matriks N = 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
#tipe 2.20.5
import numpy as np
#Misal diberikan sebuah matriks B yaitu
B_05 = np.array([
    [1,0,2],
    [0,1,3],
    [3,1,1],])
print(B_05)
A_05= np.array([
    [1,5,7],
    [2,4,1],
    [2,3,1]])
print(A_05)
print(" ")
#Tentukan beberapa operasi matematika tersebut
tanya_1_05 = 3*B_05
print(tanya_1_05)
tanya_2_05 = A_05*B_05
print(tanya_2_05)
tanya_3_05 = A_05*2
print(tanya_3_05)
tanya_4_05 = B_05/A_05
print(tanya_4_05)

[[1 0 2]
 [0 1 3]
 [3 1 1]]
[[1 5 7]
 [2 4 1]
 [2 3 1]]
 
[[3 0 6]
 [0 3 9]
 [9 3 3]]
[[ 1  0 14]
 [ 0  4  3]
 [ 6  3  1]]
[[ 2 10 14]
 [ 4  8  2]
 [ 4  6  2]]
[[1.         0.         0.28571429]
 [0.         0.25       3.        ]
 [1.5        0.33333333 1.        ]]


In [8]:
#tipe 2.20.2 & tipe 2.20.7
import numpy as np

matriks_A_05 = np.array([[1,0,4,3],[2,1,3,1],[1,3,0,2]])
matriks_B_05 = np.array([[3,2,1],[1,4,1],[2,3,4]])
matriks_C_05 = np.array([[0,0,1],[2,1,1],[1,4,3]])
print(matriks_A_05)
print(matriks_B_05)
print(matriks_C_05)
print(" ")
pernyataan1_05 = matriks_A_05[0,2]
print(pernyataan1_05)
pernyataan2_05 = matriks_C_05[1,0]
print(pernyataan2_05)
print(" ")
#Melalui program diatas juga,tentukan nilai max dan min dari beberapa matriks
print("Berapa nilai maximum B dan nilai minimum C")
print ("Nilai minimum matriks B adalah ")
P1_05= np.min(matriks_B_05)
print(P2_05)
print("Nilai maximum matriks C adalah")
P2_05 = np.max(matriks_C_05)
print(P1_05)

[[1 0 4 3]
 [2 1 3 1]
 [1 3 0 2]]
[[3 2 1]
 [1 4 1]
 [2 3 4]]
[[0 0 1]
 [2 1 1]
 [1 4 3]]
 
4
2
 
Berapa nilai maximum B dan nilai minimum C
Nilai minimum matriks B adalah 
4
Nilai maximum matriks C adalah
1
